### ISSUE TITLE
Invalid type used as key - facade.php

### ISSUE THREAD

**Issue by cscd98** [danslo/hhvm#14]
Hi, Just trying this for the first time, managed to get the home page/category pages working but I am getting the following when viewing a product page:

```
Warning: Invalid operand type was used: Invalid type used as key  in /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Block/Template/Facade.php on line 83

#0 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Block/Template/Facade.php(83): mageCoreErrorHandler()
#1 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Block/Abstract.php(489): Mage_Core_Block_Template_Facade->ifEquals()
#2 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Model/Layout.php(348): Mage_Core_Block_Abstract->unsetCallChild()
#3 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Model/Layout.php(214): Mage_Core_Model_Layout->_generateAction()
#4 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks()
#5 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Cms/Helper/Page.php(113): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage()
#9 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Cms/controllers/IndexController.php(75): Mage_Cms_Helper_Page->renderPage()
#10 /var/www/vhosts/magento-capistrano/releases/20131028151316/app/code/local/Vax/Cms/controllers/IndexController.php(58): Mage_Cms_IndexController->noRouteAction()
#11 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Vax_Cms_IndexController->noRouteAction()
#12 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch()
#13 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match()
#14 /var/www/vhosts/magento-capistrano/current/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#15 /var/www/vhosts/magento-capistrano/current/app/Mage.php(683): Mage_Core_Model_App->run()
#16 /var/www/vhosts/magento-capistrano/current/index.php(112): Mage::run()
#17 {main}
```

**Comment by danslo** [comment]
I'm almost positive that this is another SimpleXML bug. This should be fixed when I finish my work in the `simplexml-refactor` branch. Thanks for reporting!

**Comment by cscd98** [comment]
Thanks! Has this been merged into master?

**Comment by danslo** [comment]
@craigcarnell I'm not sure why we were tagged here, but that commit doesn't solve thiss issue.

The simplexml-refactor branch is still a work in progress and has not been merged anywhere yet.

**Comment by cscd98** [comment]
OK Thanks for the update

**Comment by danslo** [comment]
Closing this out because of the simplexml rewrite. If you find time, please retest this bug with my simplexml-refactor branch.
