### ISSUE TITLE
 Redis doesn't work as cache backend.

### ISSUE THREAD

**Issue by danslo** [danslo/hhvm#24]
```
Invalid response: �OEn�e�3"��s���O/�]c��9��@��]n�J6���i��P��j�b�t������

#0 /home/daniel/Code/<redacted>/lib/Credis/Client.php(547): Credis_Client->read_reply()
#1 /home/daniel/Code/<redacted>/app/code/community/Cm/Cache/Backend/Redis.php(184): Credis_Client->__call()
#2 /home/daniel/Code/<redacted>/lib/Zend/Cache/Core.php(303): Cm_Cache_Backend_Redis->load()
#3 /home/daniel/Code/<redacted>/lib/Varien/Cache/Core.php(158): Zend_Cache_Core->load()
#4 /home/daniel/Code/<redacted>/lib/Varien/Db/Adapter/Pdo/Mysql.php(1472): Varien_Cache_Core->load()
#5 /home/daniel/Code/<redacted>/lib/Varien/Db/Adapter/Pdo/Mysql.php(1594): Varien_Db_Adapter_Pdo_Mysql->loadDdlCache()
#6 /home/daniel/Code/<redacted>/app/code/core/Enterprise/SalesArchive/Model/Resource/Setup.php(126): Varien_Db_Adapter_Pdo_Mysql->describeTable()
#7 /home/daniel/Code/<redacted>/app/code/core/Enterprise/SalesArchive/Model/Resource/Setup.php(91): Enterprise_SalesArchive_Model_Resource_Setup->_syncTable()
#8 /home/daniel/Code/<redacted>/app/code/core/Enterprise/SalesArchive/Model/Resource/Setup.php(76): Enterprise_SalesArchive_Model_Resource_Setup->_syncArchiveStructure()
#9 /home/daniel/Code/<redacted>/app/code/core/Mage/Core/Model/Resource/Setup.php(242): Enterprise_SalesArchive_Model_Resource_Setup->afterApplyAllUpdates()
#10 /home/daniel/Code/<redacted>/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#11 /home/daniel/Code/<redacted>/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#12 /home/daniel/Code/<redacted>/app/Mage.php(683): Mage_Core_Model_App->run()
#13 /home/daniel/Code/<redacted>/index.php(156): Mage::run()
#14 {main}
```

**Comment by danslo** [comment]
Fixed per c7ab1ae5267291903121f682ad926396022994ea. PR needs merging.
